In [27]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [28]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

## Data Preprocessing
* Replace all the NaN values in the experience columns with zero
* convert the experience columns to numbers
* Replace all the NaN values in the test_score with median

In [29]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [30]:
from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [32]:
import math
test_score_median = math.floor(df["test_score(out of 10)"].median())
test_score_median

8

In [33]:
df["test_score(out of 10)"] = df["test_score(out of 10)"].fillna(test_score_median)

In [34]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [36]:
reg = linear_model.LinearRegression()
reg.fit(df[["experience","test_score(out of 10)","interview_score(out of 10)"]],df["salary($)"])

LinearRegression()

In [37]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [38]:
reg.intercept_

17737.263464337695

In [39]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [42]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [44]:
import pickle
pickle.dump(reg,open("hiring_salary_generator_multivariant_linear_regression.pkl","wb"))